name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Cho phép chạy thủ công

permissions:
  contents: write
  actions: read
  pull-requests: write
  issues: write

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'
        channel: 'stable'
        cache: true
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        build-tools: 34.0.0
        
    - name: Accept Android licenses
      run: |
        yes | flutter doctor --android-licenses || true
        
    - name: Flutter doctor
      run: flutter doctor -v
      working-directory: ./ai_image_editor_flutter
    
    - name: Install dependencies
      run: flutter pub get
      working-directory: ./ai_image_editor_flutter
    
    - name: Clean and prepare project
      run: |
        flutter clean
        flutter pub get
      working-directory: ./ai_image_editor_flutter
        
    - name: Check Gradle setup
      run: |
        cd android
        ls -la
        ls -la gradle/wrapper/
        # Verify gradlew exists and is executable
        if [ ! -f gradlew ]; then
          echo "ERROR: gradlew file not found"
          exit 1
        fi
        if [ ! -x gradlew ]; then
          echo "Making gradlew executable..."
          chmod +x gradlew
        fi
        # Verify gradle-wrapper.jar exists
        if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
          echo "ERROR: gradle-wrapper.jar not found"
          exit 1
        fi
        echo "Gradle setup complete"
      working-directory: ./ai_image_editor_flutter
    
    - name: Analyze Dart code
      run: flutter analyze
      working-directory: ./ai_image_editor_flutter
      continue-on-error: false
    
    - name: Build Release APK
      run: |
        flutter clean
        flutter pub get
        flutter build apk --release --verbose --no-tree-shake-icons --no-shrink
      working-directory: ./ai_image_editor_flutter

    
    - name: Build Split APKs (optional)
      run: |
        flutter build apk --release --split-per-abi --verbose --no-tree-shake-icons --no-shrink || echo "Split APK build failed, continuing with universal APK"
      working-directory: ./ai_image_editor_flutter
      continue-on-error: true
    
    - name: Check APK exists
      run: |
        ls -la build/app/outputs/flutter-apk/
      working-directory: ./ai_image_editor_flutter
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: ai_image_editor_flutter/build/app/outputs/flutter-apk/app-release.apk
        if-no-files-found: warn
    
    - name: Upload Split APKs
      uses: actions/upload-artifact@v4
      with:
        name: split-apks
        path: |
          ai_image_editor_flutter/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          ai_image_editor_flutter/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          ai_image_editor_flutter/build/app/outputs/flutter-apk/app-x86_64-release.apk
      continue-on-error: true
    
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Photo Magic v1.0.${{ github.run_number }}
        body: |
          Photo Magic - AI Image Editor APK
          
          New features:
          - Background removal
          - Object cleanup  
          - Text removal
          - Image uncrop
          - Image upscaling
          - Reimagine
          - Product photography
          - Background replacement
          - Text-to-image
          
          Improvements:
          - API failover system
          - Vietnamese interface
          - Android 5.0+ support
          - Real-time processing
        files: ai_image_editor_flutter/build/app/outputs/flutter-apk/app-release.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
